---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: yes
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

    - name: "Creates directory"
      file:
        path: "/home/ubuntu/backend"
        state: "directory"
        mode: 0755

    - name: "Copy compressed backend folder"
      copy:
        src: "../../artifact.tar.gz"
        dest: "/home/ubuntu/backend/artifact.tar.gz"

    - name: "Extract backend"
      unarchive:
        remote_src: yes
        src: "/home/ubuntu/backend/artifact.tar.gz"
        dest: "/home/ubuntu/backend"

    - name: "Run the web server"
      shell:
        cmd: |
          cd /home/ubuntu/backend
          npm install
          npm i -g pm2
          pm2 stop default
          pm2 start npm -- start --wait-ready