---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy
  tasks:
    - name: "Creates directory"
      file:
        path: "~/project"
        state: "directory"
        mode: 0755

    - name: "Copy compressed backend folder"
      copy:
        src: "/root/project/backend/artifact.tar.gz"
        dest: "~/project/artifact.tar.gz"

    - name: "Extract backend"
      unarchive:
        remote_src: yes
        src: "~/project/artifact.tar.gz"
        dest: "~/project"

    - name: "Run the web server"
      shell:
        cmd: |
          cd ~/project
          npm install
          pm2 stop default
          pm2 start npm -- start --wait-ready