---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy

- name: "Copy compressed backend folder"
  copy:
    src: "artifact-backend.tar.gz"
    dest: "~/artifact-backend.tar.gz"

- name: "Extract backend"
  unarchive:
    remote_src: yes
    src: "~/artifact-backend.tar.gz"
    dest: "~/project"

- name: "Run the web server"
  shell:
    cmd: |
      cd ~/project
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready